#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmApp.Assets
{
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

#line 1 "RazorDrugDetails.cshtml"
using PharmApp.DrugsInfo;

#line default
#line hidden

#line 2 "RazorDrugDetails.cshtml"
using PharmApp.Models;

#line default
#line hidden


[System.CodeDom.Compiler.GeneratedCodeAttribute("RazorTemplatePreprocessor", "16.9.0.273")]
public partial class RazorDrugDetails : RazorDrugDetailsBase
{

#line hidden

#line 4 "RazorDrugDetails.cshtml"
public TblDrugsInfo Model { get; set; }

#line default
#line hidden


public override void Execute()
{
WriteLiteral("\r\n");

WriteLiteral("<html>\r\n<head>\r\n\r\n    <link");

WriteLiteral(" href=\"style.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(">\r\n    <link");

WriteLiteral(" href=\"framework.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(">\r\n    <link");

WriteLiteral(" href=\"owl.theme.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(">\r\n    <link");

WriteLiteral(" href=\"swipebox.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(">\r\n    <link");

WriteLiteral(" href=\"font-awesome.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(">\r\n    <link");

WriteLiteral(" href=\"font-awesome2.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteLiteral(" href=\"animate.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(">\r\n    <link");

WriteLiteral(" href=\"bootstrap-theme.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteLiteral(" href=\"bootstrap.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <script");

WriteLiteral(" src=\"lastVersionJquery.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"jquery.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"jqueryui.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"framework.plugins.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"custom.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"bootstrap.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"Search2.js\"");

WriteLiteral("></script>\r\n\r\n\r\n\r\n\r\n</head>\r\n<body>\r\n    <div");

WriteLiteral(" id=\"preloader\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" id=\"status\"");

WriteLiteral(">\r\n            <p");

WriteLiteral(" class=\"center-text\"");

WriteLiteral(" dir=\"rtl\"");

WriteLiteral(">\r\n                صبور باشید ....\r\n            </p>\r\n        </div>\r\n    </div>\r" +
"\n\r\n    <div");

WriteLiteral(" class=\"menu-wrapper\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"menu\"");

WriteLiteral(">\r\n            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" list=\"list1\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"txtsearch\"");

WriteLiteral(" onkeyup=\"DrugsInfoInterFace.SearchByName(this.value)\"");

WriteLiteral(" dir=\"rtl\"");

WriteLiteral(" class=\"contactField requiredField\"");

WriteLiteral(" name=\"name\"");

WriteLiteral(" placeholder=\"کلمه مورد نظر وارد کنید ....\"");

WriteLiteral(" value=\"\"");

WriteLiteral(" />\r\n            </a>\r\n\r\n        </div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"header\"");

WriteLiteral(">\r\n        <img");

WriteLiteral(" src=\"LogoBackWhite.png\"");

WriteLiteral(" class=\"main-logo\"");

WriteLiteral(" alt=\"Alternate Text\"");

WriteLiteral(" />\r\n        ");

WriteLiteral("\r\n        <div");

WriteLiteral(" class=\"header-controls\"");

WriteLiteral(">\r\n            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"open-more\"");

WriteLiteral("><img");

WriteLiteral(" src=\"Menu.png\"");

WriteLiteral(" width=\"20\"");

WriteLiteral(" height=\"20\"");

WriteLiteral(" /></a>\r\n            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"open-slide\"");

WriteLiteral("><img");

WriteLiteral(" src=\"Search.png\"");

WriteLiteral(" width=\"20\"");

WriteLiteral(" height=\"20\"");

WriteLiteral(" /></a>\r\n        </div>\r\n    </div>\r\n\r\n    <div");

WriteLiteral(" class=\"all-elements\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"snap-drawers\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"snap-drawer snap-drawer-right\"");

WriteLiteral(">\r\n\r\n\r\n                <div");

WriteLiteral(" class=\"sidebar-divider\"");

WriteLiteral(">\r\n                </div>\r\n\r\n                <ul");

WriteLiteral(" class=\"sidebar-navigation\"");

WriteLiteral(" dir=\"rtl\"");

WriteLiteral(" style=\"padding-right:10px;\"");

WriteLiteral(">\r\n                    <li><a");

WriteLiteral(" onclick=\"DrugsInfoInterFace.RedirectHelpView()\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(" style=\"color:black\"");

WriteLiteral(">راهنمای کاربری</a></li>\r\n                    <li><a");

WriteLiteral(" onclick=\"DrugsInfoInterFace.RedirectAboutUs()\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(" style=\"color:black\"");

WriteLiteral(">درباره ما</a></li>\r\n                    <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" style=\"color:black\"");

WriteLiteral(">خروج</a></li>\r\n\r\n                </ul>\r\n\r\n                <div");

WriteLiteral(" class=\"sidebar-divider\"");

WriteLiteral(">\r\n                    Physical Properties All Rights Reserved 2021\r\n            " +
"    </div>\r\n            </div>\r\n        </div>\r\n\r\n        <!-- Page Content-->\r\n" +
"        <div");

WriteLiteral(" id=\"content\"");

WriteLiteral(" class=\"snap-content\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"header-clear\"");

WriteLiteral("></div>\r\n\r\n            <div>\r\n                <div");

WriteLiteral(" class=\"staff-item\"");

WriteLiteral(">\r\n                    <img");

WriteLiteral(" src=\"LogoBackBlack.png\"");

WriteLiteral(" />\r\n                    ");

WriteLiteral("\r\n                </div>\r\n            </div>\r\n\r\n\r\n           \r\n            <div");

WriteLiteral(" class=\"content text-justify\"");

WriteLiteral(" id=\"divdrugslist\"");

WriteLiteral(">\r\n\r\n                <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"one-half\"");

WriteLiteral(">\r\n                        <p>\r\n                            <h3");

WriteLiteral(" dir=\"ltr\"");

WriteLiteral(">");


#line 97 "RazorDrugDetails.cshtml"
                                     Write(Model.EnglishName);


#line default
#line hidden
WriteLiteral("</h3><br>\r\n                        </p>\r\n                    </div>\r\n            " +
"        <div");

WriteLiteral(" class=\"two-half last-column\"");

WriteLiteral(">\r\n                        <p>\r\n                            <h4");

WriteLiteral(" dir=\"rtl\"");

WriteLiteral(">");


#line 102 "RazorDrugDetails.cshtml"
                                     Write(Model.PersianName);


#line default
#line hidden
WriteLiteral("</h4><br>\r\n\r\n                        </p>\r\n                    </div>\r\n          " +
"      </div>\r\n\r\n\r\n\r\n                <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"toggle-1\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" dir=\"rtl\"");

WriteLiteral(" class=\"deploy-toggle-1\"");

WriteLiteral(">\r\n                            نام علمی\r\n                        </a>\r\n          " +
"              <div");

WriteLiteral(" class=\"toggle-content\"");

WriteLiteral(">\r\n                            <p");

WriteLiteral(" id=\"pg111\"");

WriteLiteral(" dir=\"rtl\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");


#line 117 "RazorDrugDetails.cshtml"
                           Write(Model.CommercialName);


#line default
#line hidden
WriteLiteral("\r\n                            </p>\r\n                        </div>\r\n             " +
"       </div>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"toggle-1\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" dir=\"rtl\"");

WriteLiteral(" class=\"deploy-toggle-1\"");

WriteLiteral(">\r\n                            نوع\r\n                        </a>\r\n               " +
"         <div");

WriteLiteral(" class=\"toggle-content\"");

WriteLiteral(">\r\n                            <p");

WriteLiteral(" id=\"pg144\"");

WriteLiteral(" dir=\"rtl\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");


#line 130 "RazorDrugDetails.cshtml"
                           Write(Model.Type);


#line default
#line hidden
WriteLiteral("\r\n                            </p>\r\n                        </div>\r\n             " +
"       </div>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"toggle-1\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" dir=\"rtl\"");

WriteLiteral(" class=\"deploy-toggle-1\"");

WriteLiteral(">\r\n                            درصد همکشیدگی کل\r\n                        </a>\r\n  " +
"                      <div");

WriteLiteral(" class=\"toggle-content\"");

WriteLiteral(">\r\n                            <p");

WriteLiteral(" id=\"pg\"");

WriteLiteral(" dir=\"rtl\"");

WriteLiteral(" style=\"white-space:pre-line; text-align:right;\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");


#line 143 "RazorDrugDetails.cshtml"
                           Write(Model.PercentageTotalSolidity);


#line default
#line hidden
WriteLiteral("\r\n                            </p>\r\n                        </div>\r\n             " +
"       </div>\r\n                </div>\r\n\r\n\r\n\r\n\r\n\r\n                <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"toggle-1\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" dir=\"rtl\"");

WriteLiteral(" class=\"deploy-toggle-1\"");

WriteLiteral(">\r\n                            ضریب تغییرات ابعادی\r\n                        </a>\r" +
"\n                        <div");

WriteLiteral(" class=\"toggle-content\"");

WriteLiteral(">\r\n\r\n                            <p");

WriteLiteral(" id=\"pg2\"");

WriteLiteral(" dir=\"rtl\"");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(" style=\"white-space:pre-line; text-align:right;\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");


#line 161 "RazorDrugDetails.cshtml"
                           Write(Model.DimensionalChangeCoefficient);


#line default
#line hidden
WriteLiteral("\r\n                            </p>\r\n                        </div>\r\n             " +
"       </div>\r\n                </div>\r\n\r\n\r\n                <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"toggle-1\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" dir=\"rtl\"");

WriteLiteral(" class=\"deploy-toggle-1\"");

WriteLiteral(">\r\n                            درصد همکشیدگی\r\n\r\n                        </a>\r\n   " +
"                     <div");

WriteLiteral(" class=\"toggle-content\"");

WriteLiteral(">\r\n                            <p");

WriteLiteral(" id=\"pg3\"");

WriteLiteral(" dir=\"rtl\"");

WriteLiteral(" style=\"white-space:pre-line; text-align:left\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");


#line 176 "RazorDrugDetails.cshtml"
                           Write(Model.PercentageCohesion);


#line default
#line hidden
WriteLiteral("\r\n                            </p>\r\n                        </div>\r\n             " +
"       </div>\r\n                </div>\r\n\r\n\r\n                <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"toggle-1\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" dir=\"rtl\"");

WriteLiteral(" class=\"deploy-toggle-1\"");

WriteLiteral(">\r\n                            \"میانگین  درصد\r\n                            رطوبت " +
"چوب سبز\"\r\n\r\n                        </a>\r\n                        <div");

WriteLiteral(" class=\"toggle-content\"");

WriteLiteral(">\r\n                            <p");

WriteLiteral(" id=\"pg4\"");

WriteLiteral(" dir=\"rtl\"");

WriteLiteral(" style=\"white-space:pre-line; text-align:right;\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");


#line 192 "RazorDrugDetails.cshtml"
                           Write(Model.AverageMoistureContentGreenWood);


#line default
#line hidden
WriteLiteral("\r\n                            </p>\r\n                        </div>\r\n             " +
"       </div>\r\n                </div>\r\n\r\n\r\n                <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"toggle-1\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" dir=\"rtl\"");

WriteLiteral(" class=\"deploy-toggle-1\"");

WriteLiteral(">\r\n                            وزن مخصوص در رطوبت\r\n\r\n                        </a>" +
"\r\n                        <div");

WriteLiteral(" class=\"toggle-content\"");

WriteLiteral(">\r\n                            <p");

WriteLiteral(" id=\"pg5\"");

WriteLiteral(" dir=\"rtl\"");

WriteLiteral(" style=\"white-space:pre-line; text-align:right;\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");


#line 207 "RazorDrugDetails.cshtml"
                           Write(Model.SpecificGravityMoisture);


#line default
#line hidden
WriteLiteral("\r\n                            </p>\r\n                        </div>\r\n             " +
"       </div>\r\n                </div>\r\n\r\n\r\n\r\n               \r\n                <d" +
"iv");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"toggle-1\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" dir=\"rtl\"");

WriteLiteral(" class=\"deploy-toggle-1\"");

WriteLiteral("> توضیحات بیشتر</a>\r\n                        <div");

WriteLiteral(" class=\"toggle-content\"");

WriteLiteral(">\r\n");


#line 220 "RazorDrugDetails.cshtml"
                            

#line default
#line hidden

#line 220 "RazorDrugDetails.cshtml"
                             if (@Model.ImageLinkAddress != null)
                            {


#line default
#line hidden
WriteLiteral("                                <img");

WriteAttribute ("src", " src=\"", "\""

#line 222 "RazorDrugDetails.cshtml"
   , Tuple.Create<string,object,bool> ("", Model.ImageLinkAddress

#line default
#line hidden
, false)
);
WriteLiteral(" alt=\"UniFarmer\"");

WriteLiteral(" />\r\n");


#line 223 "RazorDrugDetails.cshtml"
                            }


#line default
#line hidden
WriteLiteral("                            ");


#line 224 "RazorDrugDetails.cshtml"
                             if (@Model.Des != null)
                            {


#line default
#line hidden
WriteLiteral("                                <p");

WriteLiteral(" id=\"pg18\"");

WriteLiteral(" dir=\"rtl\"");

WriteLiteral(" style=\"white-space:pre-line; text-align:right;\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");


#line 227 "RazorDrugDetails.cshtml"
                               Write(Model.Des);


#line default
#line hidden
WriteLiteral("\r\n                                </p>\r\n");


#line 229 "RazorDrugDetails.cshtml"
                            }


#line default
#line hidden
WriteLiteral("                            ");


#line 230 "RazorDrugDetails.cshtml"
                             if (@Model.ImageLinkAddress1 != null)
                            {



#line default
#line hidden
WriteLiteral("                                <img");

WriteAttribute ("src", " src=\"", "\""

#line 233 "RazorDrugDetails.cshtml"
   , Tuple.Create<string,object,bool> ("", Model.ImageLinkAddress1

#line default
#line hidden
, false)
);
WriteLiteral(" alt=\"UniFarmer\"");

WriteLiteral(" />\r\n");


#line 234 "RazorDrugDetails.cshtml"
                            }


#line default
#line hidden
WriteLiteral("                            ");


#line 235 "RazorDrugDetails.cshtml"
                             if (@Model.Des1 != null)
                            {



#line default
#line hidden
WriteLiteral("                                <p");

WriteLiteral(" id=\"pg19\"");

WriteLiteral(" dir=\"rtl\"");

WriteLiteral(" style=\"white-space:pre-line; text-align:right;\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");


#line 239 "RazorDrugDetails.cshtml"
                               Write(Model.Des1);


#line default
#line hidden
WriteLiteral("\r\n                                </p>\r\n");


#line 241 "RazorDrugDetails.cshtml"
                            }


#line default
#line hidden
WriteLiteral("                            ");


#line 242 "RazorDrugDetails.cshtml"
                             if (@Model.ImageLinkAddress2 != null)
                            {


#line default
#line hidden
WriteLiteral("                                <img");

WriteAttribute ("src", " src=\"", "\""

#line 244 "RazorDrugDetails.cshtml"
   , Tuple.Create<string,object,bool> ("", Model.ImageLinkAddress2

#line default
#line hidden
, false)
);
WriteLiteral(" alt=\"UniFarmer\"");

WriteLiteral(" />\r\n");


#line 245 "RazorDrugDetails.cshtml"
                            }


#line default
#line hidden
WriteLiteral("                            ");


#line 246 "RazorDrugDetails.cshtml"
                             if (@Model.Des2 != null)
                            {


#line default
#line hidden
WriteLiteral("                                <p");

WriteLiteral(" id=\"pg20\"");

WriteLiteral(" dir=\"rtl\"");

WriteLiteral(" style=\"white-space:pre-line; text-align:right;\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");


#line 249 "RazorDrugDetails.cshtml"
                               Write(Model.Des2);


#line default
#line hidden
WriteLiteral("\r\n                                </p>\r\n");


#line 251 "RazorDrugDetails.cshtml"
                            }


#line default
#line hidden
WriteLiteral("                        </div>\r\n                    </div>\r\n                </div" +
">\r\n\r\n            </div>\r\n\r\n\r\n        </div>\r\n    </div>\r\n\r\n\r\n<script");

WriteLiteral(" src=\"WordColorChecker.js\"");

WriteLiteral("></script>\r\n</body>\r\n\r\n</html>");

}
}

// NOTE: this is the default generated helper class. You may choose to extract it to a separate file 
// in order to customize it or share it between multiple templates, and specify the template's base 
// class via the @inherits directive.
public abstract class RazorDrugDetailsBase
{

		// This field is OPTIONAL, but used by the default implementation of Generate, Write, WriteAttribute and WriteLiteral
		//
		System.IO.TextWriter __razor_writer;

		// This method is OPTIONAL
		//
		/// <summary>Executes the template and returns the output as a string.</summary>
		/// <returns>The template output.</returns>
		public string GenerateString ()
		{
			using (var sw = new System.IO.StringWriter ()) {
				Generate (sw);
				return sw.ToString ();
			}
		}

		// This method is OPTIONAL, you may choose to implement Write and WriteLiteral without use of __razor_writer
		// and provide another means of invoking Execute.
		//
		/// <summary>Executes the template, writing to the provided text writer.</summary>
		/// <param name="writer">The TextWriter to which to write the template output.</param>
		public void Generate (System.IO.TextWriter writer)
		{
			__razor_writer = writer;
			Execute ();
			__razor_writer = null;
		}

		// This method is REQUIRED, but you may choose to implement it differently
		//
		/// <summary>Writes a literal value to the template output without HTML escaping it.</summary>
		/// <param name="value">The literal value.</param>
		protected void WriteLiteral (string value)
		{
			__razor_writer.Write (value);
		}

		// This method is REQUIRED if the template contains any Razor helpers, but you may choose to implement it differently
		//
		/// <summary>Writes a literal value to the TextWriter without HTML escaping it.</summary>
		/// <param name="writer">The TextWriter to which to write the literal.</param>
		/// <param name="value">The literal value.</param>
		protected static void WriteLiteralTo (System.IO.TextWriter writer, string value)
		{
			writer.Write (value);
		}

		// This method is REQUIRED, but you may choose to implement it differently
		//
		/// <summary>Writes a value to the template output, HTML escaping it if necessary.</summary>
		/// <param name="value">The value.</param>
		/// <remarks>The value may be a Action<System.IO.TextWriter>, as returned by Razor helpers.</remarks>
		protected void Write (object value)
		{
			WriteTo (__razor_writer, value);
		}

		// This method is REQUIRED if the template contains any Razor helpers, but you may choose to implement it differently
		//
		/// <summary>Writes an object value to the TextWriter, HTML escaping it if necessary.</summary>
		/// <param name="writer">The TextWriter to which to write the value.</param>
		/// <param name="value">The value.</param>
		/// <remarks>The value may be a Action<System.IO.TextWriter>, as returned by Razor helpers.</remarks>
		protected static void WriteTo (System.IO.TextWriter writer, object value)
		{
			if (value == null)
				return;

			var write = value as Action<System.IO.TextWriter>;
			if (write != null) {
				write (writer);
				return;
			}

			//NOTE: a more sophisticated implementation would write safe and pre-escaped values directly to the
			//instead of double-escaping. See System.Web.IHtmlString in ASP.NET 4.0 for an example of this.
			writer.Write(System.Net.WebUtility.HtmlEncode (value.ToString ()));
		}

		// This method is REQUIRED, but you may choose to implement it differently
		//
		/// <summary>
		/// Conditionally writes an attribute to the template output.
		/// </summary>
		/// <param name="name">The name of the attribute.</param>
		/// <param name="prefix">The prefix of the attribute.</param>
		/// <param name="suffix">The suffix of the attribute.</param>
		/// <param name="values">Attribute values, each specifying a prefix, value and whether it's a literal.</param>
		protected void WriteAttribute (string name, string prefix, string suffix, params Tuple<string,object,bool>[] values)
		{
			WriteAttributeTo (__razor_writer, name, prefix, suffix, values);
		}

		// This method is REQUIRED if the template contains any Razor helpers, but you may choose to implement it differently
		//
		/// <summary>
		/// Conditionally writes an attribute to a TextWriter.
		/// </summary>
		/// <param name="writer">The TextWriter to which to write the attribute.</param>
		/// <param name="name">The name of the attribute.</param>
		/// <param name="prefix">The prefix of the attribute.</param>
		/// <param name="suffix">The suffix of the attribute.</param>
		/// <param name="values">Attribute values, each specifying a prefix, value and whether it's a literal.</param>
		///<remarks>Used by Razor helpers to write attributes.</remarks>
		protected static void WriteAttributeTo (System.IO.TextWriter writer, string name, string prefix, string suffix, params Tuple<string,object,bool>[] values)
		{
			// this is based on System.Web.WebPages.WebPageExecutingBase
			// Copyright (c) Microsoft Open Technologies, Inc.
			// Licensed under the Apache License, Version 2.0
			if (values.Length == 0) {
				// Explicitly empty attribute, so write the prefix and suffix
				writer.Write (prefix);
				writer.Write (suffix);
				return;
			}

			bool first = true;
			bool wroteSomething = false;

			for (int i = 0; i < values.Length; i++) {
				Tuple<string,object,bool> attrVal = values [i];
				string attPrefix = attrVal.Item1;
				object value = attrVal.Item2;
				bool isLiteral = attrVal.Item3;

				if (value == null) {
					// Nothing to write
					continue;
				}

				// The special cases here are that the value we're writing might already be a string, or that the
				// value might be a bool. If the value is the bool 'true' we want to write the attribute name instead
				// of the string 'true'. If the value is the bool 'false' we don't want to write anything.
				//
				// Otherwise the value is another object (perhaps an IHtmlString), and we'll ask it to format itself.
				string stringValue;
				bool? boolValue = value as bool?;
				if (boolValue == true) {
					stringValue = name;
				} else if (boolValue == false) {
					continue;
				} else {
					stringValue = value as string;
				}

				if (first) {
					writer.Write (prefix);
					first = false;
				} else {
					writer.Write (attPrefix);
				}

				if (isLiteral) {
					writer.Write (stringValue ?? value);
				} else {
					WriteTo (writer, stringValue ?? value);
				}
				wroteSomething = true;
			}
			if (wroteSomething) {
				writer.Write (suffix);
			}
		}
		// This method is REQUIRED. The generated Razor subclass will override it with the generated code.
		//
		///<summary>Executes the template, writing output to the Write and WriteLiteral methods.</summary>.
		///<remarks>Not intended to be called directly. Call the Generate method instead.</remarks>
		public abstract void Execute ();

}
}
#pragma warning restore 1591
